export const INDIAN_STATES = [
  "Tamil Nadu",
  "Kerala",
  "Karnataka",
  "Andhra Pradesh",
  "Telangana",
  "Puducherry",
  "Goa",
  "Himachal Pradesh",
  "Uttarakhand",
  "Ladakh",
  "Rajasthan",
  "Maharashtra",
  "Sikkim",
  "Meghalaya",
  "Uttar Pradesh",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Gujarat",
  "Haryana",
  "Jammu and Kashmir",
  "Jharkhand",
  "Madhya Pradesh",
  "Manipur",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Tripura",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Lakshadweep"
];

export const TOP_LOCATIONS = [
  { name: "Kanyakumari", state: "Tamil Nadu", tag: "கன்னியாகுமரி" },
  { name: "Rameshwaram", state: "Tamil Nadu", tag: "ராமேஸ்வரம்" },
  { name: "Ooty & Nilgiris", state: "Tamil Nadu", tag: "நீலகிரி" },
  { name: "Kodaikanal", state: "Tamil Nadu", tag: "கொடைக்கானல்" },
  { name: "Mahabalipuram", state: "Tamil Nadu", tag: "மாமல்லபுரம்" },
  { name: "Madurai", state: "Tamil Nadu", tag: "மதுரை" },
  { name: "Munnar", state: "Kerala", tag: "மூணார்" },
  { name: "Hampi", state: "Karnataka", tag: "ஹம்பி" },
  { name: "Gokarna", state: "Karnataka", tag: "கோகர்ணா" },
  { name: "Pondicherry", state: "Puducherry", tag: "புதுச்சேரி" },
  { name: "Manali", state: "Himachal Pradesh", tag: "மணாலி" },
  { name: "Varanasi", state: "Uttar Pradesh", tag: "வாரணாசி" }
];
