export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry"
];

export const TOP_LOCATIONS = [
  { name: "Manali", state: "Himachal Pradesh" },
  { name: "Leh", state: "Ladakh" },
  { name: "Varanasi", state: "Uttar Pradesh" },
  { name: "Jaipur", state: "Rajasthan" },
  { name: "Munnar", state: "Kerala" },
  { name: "Hampi", state: "Karnataka" },
  { name: "Rishikesh", state: "Uttarakhand" },
  { name: "Goa", state: "Goa" },
  { name: "Pondicherry", state: "Puducherry" },
  { name: "Darjeeling", state: "West Bengal" },
];
